apiVersion: v1
kingd: Pod
metadata:
  name: two-tier-app
spec:
  containers:
    - name: two-tier-app
      image: sachin8927/flaskapp:latest
      env:
        - name: MYSQL_HOST
          value:
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DB
          value: mydb
  ports:
    - containerPort: 5000
  imagePullPolicy: Always
