apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app
spec:
  containers:
    - name: two-tier-app
      image: sachin8927/flaskapp:latest
      env:
        - name: MYSQL_HOST
          value: 10.100.127.90 # Example: replace with your MySQL service name or IP
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DB
          value: mydb
      ports:
        - containerPort: 5000
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
      imagePullPolicy: Always
